### ISSUE TITLE
Unable to login, with both file and otp

### ISSUE THREAD

**Issue by maleeqB** [sumithemmadi/truecallerjs#14]
When I tried to login with file 

$ truecallerjs login ./my-truecaller-data-1671312322082.json

I receive the error:
```
TypeError: Cannot read properties of undefined (reading 'installations')
    at start_truecallerjs (/usr/lib/node_modules/truecallerjs/bin/index.js:425:42)
    at Object.<anonymous> (/usr/lib/node_modules/truecallerjs/bin/index.js:612:1)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47
```

When I tried otp method, I have same problem with [issue n7](https://github.com/sumithemmadi/truecallerjs/issues/7)

**Comment by sumithemmadi** [comment]
might be you have edited this *./my-truecaller-data-1671312322082.json*
send me contains of file by replacing all your details with XXXX

**Comment by maleeqB** [comment]
This is the content of the json file:


{  "userId":xxx"ip": "xxxx",  "userCountryCode": "FR",  "applicationName": "Truecaller Web",  "oauthId": "xxxx",  "provider": "google",  "createdAt": 1670079259981,  "updatedAt": 1671312322082}

**Comment by sumithemmadi** [comment]
That is not a valid json file

**Comment by maleeqB** [comment]
Not a valid truecaller file or not a valid json file?

If the latter is the case, then how is that?

That's what I downloaded from my truecaller dashboard, and that's literally a valid JSON

**Comment by sumithemmadi** [comment]
sorry , not a valid truecaller json file 

follow below steps to download correct file

https://github.com/sumithemmadi/truecallerjs#login

**Comment by maleeqB** [comment]
Ok thanks
