### ISSUE TITLE
This error just appeared today. Request failed with status code 426 AxiosError AxiosError: Request failed with status code 426

### ISSUE THREAD

**Issue by thecowmilk** [sumithemmadi/truecallerjs#46]
I don't know what happened yesterday it was fine now there's this error:

```
message             : Request failed with status code 426
name                : AxiosError
stack               : AxiosError: Request failed with status code 426
    at settle (file:///usr/local/lib/node_modules/truecallerjs/node_modules/axios/lib/core/settle.js:19:12)
    at Unzip.handleStreamEnd (file:///usr/local/lib/node_modules/truecallerjs/node_modules/axios/lib/adapters/http.js:570:11)
    at Unzip.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1376:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
config              : 
transitional        : 
silentJSONParsing   : true
forcedJSONParsing   : true
clarifyTimeoutError : false
adapter             : xhr, http
transformRequest    : null
transformResponse   : null
timeout             : 0
xsrfCookieName      : XSRF-TOKEN
xsrfHeaderName      : X-XSRF-TOKEN
maxContentLength    : -1
maxBodyLength       : -1
env                 : {}
headers             : 
Accept              : application/json, text/plain, */*
content-type        : application/json; charset=UTF-8
accept-encoding     : gzip
user-agent          : Truecaller/11.75.5 (Android;10)
params              : 
locAddr             : 
placement           : SEARCHRESULTS,HISTORY,DETAILS
encoding            : json
method              : get
url                 : https://search5-noneu.truecaller.com/v2/search
code                : ERR_BAD_REQUEST
status              : 426

```

**Comment by thecowmilk** [comment]
It changed now to:
```
message             : Request failed with status code 401
name                : AxiosError
stack               : AxiosError: Request failed with status code 401
    at settle (file:///usr/local/lib/node_modules/truecallerjs/node_modules/axios/lib/core/settle.js:19:12)
    at Unzip.handleStreamEnd (file:///usr/local/lib/node_modules/truecallerjs/node_modules/axios/lib/adapters/http.js:570:11)
    at Unzip.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1376:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
config              : 
transitional        : 
silentJSONParsing   : true
forcedJSONParsing   : true
clarifyTimeoutError : false
adapter             : xhr, http
transformRequest    : null
transformResponse   : null
timeout             : 0
xsrfCookieName      : XSRF-TOKEN
xsrfHeaderName      : X-XSRF-TOKEN
maxContentLength    : -1
maxBodyLength       : -1
env                 : {}
headers             : 
Accept              : application/json, text/plain, */*
content-type        : application/json; charset=UTF-8
accept-encoding     : gzip
user-agent          : Truecaller/11.75.5 (Android;10)
type                : 4
locAddr             : 
placement           : SEARCHRESULTS,HISTORY,DETAILS
encoding            : json
method              : get
url                 : https://search5-noneu.truecaller.com/v2/search
code                : ERR_BAD_REQUEST
status              : 401
```

**Comment by sumithemmadi** [comment]
similar to #32

**Comment by arunp7** [comment]
@sumithemmadi Hi do you have any fix for this at the moment?

**Comment by sumithemmadi** [comment]
No , i will fix it as soon as possible. 
@arunp7  if you are from india, the project will work fine. you will not get any 426 error.

**Comment by thecowmilk** [comment]
Please bro fix it as soon as possible!!

**Comment by arunp7** [comment]
Thanks. @sumithemmadi. I am from India. I have a service built on top of this, and it has not been working properly for a couple of days. Upon investigation, I discovered that this error 426 is the reason. I don't believe it's a geographical issue.

**Comment by sviatoslavPaliy** [comment]
@sumithemmadi do you have the proto file?

**Comment by MDHaarith** [comment]
i got this problem today im from india could you please help me

**Comment by sumithemmadi** [comment]
@sviatoslavPaliy  no, i don't  have proto files.

**Comment by deepesh-agarwal** [comment]
@sumithemmadi Same error, Indian number (US server IP).
