### ISSUE TITLE
Invalid phone number

### ISSUE THREAD

**Issue by frozenfox44** [sumithemmadi/truecallerjs#50]
Hello,

We used to be able to input a JSON file from Android app to login. That functionality now appears to be gone.

Instead, we try to use a phone number, but it is rejected, giving a very long error stack:

Enter your phone number : +1XXXXXXXXXX (US phone number)
```
file:///usr/local/lib/node_modules/truecallerjs/node_modules/axios/lib/core/settle.js:19
    reject(new AxiosError(
           ^
AxiosError: Request failed with status code 400
    at settle (file:///usr/local/lib/node_modules/truecallerjs/node_modules/axios/lib/core/settle.js:19:12)
    at Unzip.handleStreamEnd (file:///usr/local/lib/node_modules/truecallerjs/node_modules/axios/lib/adapters/http.js:570:11)
    at Unzip.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1376:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ERR_BAD_REQUEST',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
...
 _currentUrl: 'https://account-asia-south1.truecaller.com/v2/sendOnboardingOtp',
        [Symbol(kCapture)]: false
      },
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype] {
        accept: [ 'Accept', 'application/json, text/plain, */*' ],
        'content-type': [ 'Content-Type', 'application/json; charset=UTF-8' ],
        'accept-encoding': [ 'accept-encoding', 'gzip' ],
        'user-agent': [ 'user-agent', 'Truecaller/11.75.5 (Android;10)' ],
        clientsecret: [ 'clientsecret', 'lvc22mp3l1sfv6ujg83rd17btt' ],
        'content-length': [ 'Content-Length', '380' ],
        host: [ 'Host', 'account-asia-south1.truecaller.com' ]
      },
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    data: { status: 40003, message: 'Invalid phone number' }
```
Any idea why this may be? Android app login still works.

**Comment by sumithemmadi** [comment]
The phone number that you passed is wrong

**Comment by frozenfox44** [comment]
Wrong in what sense? I am using the same North American number that works within TrueCaller app. I use the international format, e.g +12225551212. Specifying any number in that format gives the same error.

**Comment by sumithemmadi** [comment]
Okay, I will let you know once I check it.
