### ISSUE TITLE
Request failed with status code 426

### ISSUE THREAD

**Issue by Dragonizedpizza** [sumithemmadi/truecallerjs#52]
```js
$ truecallerjs -s +9199123456789 --json
{
  "message": "Request failed with status code 426",
  "name": "AxiosError",
  "stack": "AxiosError: Request failed with status code 426\n    at settle (file:///usr/local/lib/node_modules/truecallerjs/node_modules/axios/lib/core/settle.js:19:12)\n    at Unzip.handleStreamEnd (file:///usr/local/lib/node_modules/truecallerjs/node_modules/axios/lib/adapters/http.js:572:11)\n    at Unzip.emit (node:events:523:35)\n    at endReadableNT (node:internal/streams/readable:1367:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)",
  "config": {
    "transitional": {
      "silentJSONParsing": true,
      "forcedJSONParsing": true,
      "clarifyTimeoutError": false
    },
    "adapter": "http",
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 0,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1,
    "maxBodyLength": -1,
    "env": {},
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "Content-Type": "application/json; charset=UTF-8",
      "accept-encoding": "gzip",
      "user-agent": "Truecaller/11.75.5 (Android;10)",
      "Authorization": "Bearer XXX"
    },
    "params": {
      "q": "99123456789",
      "countryCode": "IN",
      "type": 4,
      "locAddr": "",
      "placement": "SEARCHRESULTS,HISTORY,DETAILS",
      "encoding": "json"
    },
    "method": "get",
    "url": "https://search5-noneu.truecaller.com/v2/search"
  },
  "code": "ERR_BAD_REQUEST",
  "status": 426
}
```

**Comment by lonelypx** [comment]
invalid number format "q": "99123456789",

**Comment by Dragonizedpizza** [comment]
> invalid number format "q": "99123456789",

this is the command shown in the readme

**Comment by sumithemmadi** [comment]
similar to #32
