### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by KILLERYTHACK** [sumithemmadi/truecallerjs#55]
Bro there is an error
When i am using this command 
truecallerjs -s +91******** 

message             : Request failed with status code 426
name                : AxiosError
stack               : AxiosError: Request failed with status code 426
    at settle (file:///data/data/com.termux/files/usr/lib/node_modules/truecallerjs/node_modules/axios/lib/core/settle.js:19:12)
    at Unzip.handleStreamEnd (file:///data/data/com.termux/files/usr/lib/node_modules/truecallerjs/node_modules/axios/lib/adapters/http.js:572:11)
    at Unzip.emit (node:events:523:35)
    at endReadableNT (node:internal/streams/readable:1367:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
config              :
transitional        :
silentJSONParsing   : true
forcedJSONParsing   : true
clarifyTimeoutError : false
adapter             : http
transformRequest    : null
transformResponse   : null
timeout             : 0
xsrfCookieName      : XSRF-TOKEN
xsrfHeaderName      : X-XSRF-TOKEN
maxContentLength    : -1
maxBodyLength       : -1
env                 : {}
headers             :
Accept              : application/json, text/plain, */*
Content-Type        : application/json; charset=UTF-8
accept-encoding     : gzip
user-agent          : Truecaller/11.75.5 (Android;10)
Authorization       : Bearer a1i0v--i8kwv0-CV5IhmESSnwZF68UUwCB7g4TIrKToHzesVErv36k1c-6ykaFOG
params              :
q                   : *********
countryCode         : IN
type                : 4
locAddr             :
placement           : SEARCHRESULTS,HISTORY,DETAILS
encoding            : json
method              : get
url                 : https://search5-noneu.truecaller.com/v2/search
code                : ERR_BAD_REQUEST
status              : 426

**Comment by KILLERYTHACK** [comment]
Solve this error

**Comment by sumithemmadi** [comment]
similar to  #32
