### ISSUE TITLE
Request failed with status code 426

### ISSUE THREAD

**Issue by bishu** [sumithemmadi/truecallerjs#63]
in the command line when I use
truecallerjs -s +919856000000

I got an error message as -

message             : Request failed with status code 426
name                : AxiosError
stack               : AxiosError: Request failed with status code 426
    at settle (file:///www/server/nvm/versions/node/v18.18.2/lib/node_modules/truecallerjs/node_modules/axios/lib/core/settle.js:19:12)
    at Unzip.handleStreamEnd (file:///www/server/nvm/versions/node/v18.18.2/lib/node_modules/truecallerjs/node_modules/axios/lib/adapters/http.js:585:11)
    at Unzip.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1368:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
config              :
transitional        :
silentJSONParsing   : true
forcedJSONParsing   : true
clarifyTimeoutError : false
adapter             : xhr, http
transformRequest    : null
transformResponse   : null
timeout             : 0
xsrfCookieName      : XSRF-TOKEN
xsrfHeaderName      : X-XSRF-TOKEN
maxContentLength    : -1
maxBodyLength       : -1
env                 : {}
headers             :
Accept              : application/json, text/plain, */*
Content-Type        : application/json; charset=UTF-8
accept-encoding     : gzip
user-agent          : Truecaller/11.75.5 (Android;10)
Authorization       : Bearer a1i0e--jhoURDFqk3v1PXGyGjW7fXGleliiI68bBkjU2fHnQoIrOopovp74-oPT5
params              :
q                   : 9856000000
countryCode         : IN
type                : 4
locAddr             :
placement           : SEARCHRESULTS,HISTORY,DETAILS
encoding            : json
method              : get
url                 : https://search5-noneu.truecaller.com/v2/search
code                : ERR_BAD_REQUEST
status              : 426

**Comment by duplicate2991** [comment]
same problem

**Comment by adarsh-chakraborty** [comment]
same problem

**Comment by duplicate2991** [comment]
> same problem

t think its truecallers problem

**Comment by yannickcof** [comment]
same here !!!

**Comment by Cadburyash** [comment]
single search is working for me, However when I am trying to search in bulk I am getting 400 error message
