### ISSUE TITLE
(-bs) Request failed with status code 400(

### ISSUE THREAD

**Issue by Cadburyash** [sumithemmadi/truecallerjs#68]
While performing bulk search
truecallerjs -bs +91xxxxxxxxxx,+91xxxxxxxxxx

message             : Request failed with status code 400
name                : AxiosError
stack               : AxiosError: Request failed with status code 400
    at settle (file:///C:/Users/cadbu/AppData/Roaming/npm/node_modules/truecallerjs/node_modules/axios/lib/core/settle.js:19:12)
    at IncomingMessage.handleStreamEnd (file:///C:/Users/cadbu/AppData/Roaming/npm/node_modules/truecallerjs/node_modules/axios/lib/adapters/http.js:585:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
config              :
transitional        :
silentJSONParsing   : true
forcedJSONParsing   : true
clarifyTimeoutError : false
adapter             : xhr, http
transformRequest    : null
transformResponse   : null
timeout             : 0
xsrfCookieName      : XSRF-TOKEN
xsrfHeaderName      : X-XSRF-TOKEN
maxContentLength    : -1
maxBodyLength       : -1
env                 : {}
headers             :
Accept              : application/json, text/plain, */*
Content-Type        : application/json; charset=UTF-8
accept-encoding     : gzip
user-agent          : Truecaller/11.75.5 (Android;10)
Authorization       : Bearer a1i0---k21CQBk8-rVvMODDcGJMOgSRinWBUAR25Eb8S75Aju6H241qTj75KfHP-
params              :
countryCode         : IN
type                : 4
locAddr             :
placement           : SEARCHRESULTS,HISTORY,DETAILS
encoding            : json
method              : get
url                 : https://search5-noneu.truecaller.com/v2/search
code                : ERR_BAD_REQUEST
status              : 400

![image](https://github.com/sumithemmadi/truecallerjs/assets/73462373/bc56f77a-0841-4864-90cf-687aa04f35b9)

**Comment by Cadburyash** [comment]
With an extra space before the second parameter it shows name of first number>>

![image](https://github.com/sumithemmadi/truecallerjs/assets/73462373/d1d6c851-e1e3-4a31-8ef3-e168cdce4e65)

**Comment by abhishek03690** [comment]
Is that problem fixed? If it is then, please tell me how to solve it for single number only.

**Comment by HalibHack** [comment]
did u found something
